# Generated by Django 4.2.24 on 2025-11-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=800, null=True, verbose_name='Desciption'),
        ),
    ]
