# Generated by Django 4.2.24 on 2025-12-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=800, null=True, verbose_name='Desciption'),
        ),
    ]
