# Generated by Django 4.2.24 on 2025-12-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_remove_book_isbn_book_description'),
    ]

    operations = [
    ]
