# Generated by Django 4.2.24 on 2025-12-10 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_add_readingroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='author',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ReadingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "Читальный зал №1" или "Зал научной литературы"', max_length=200, verbose_name='название читального зала')),
                ('capacity', models.PositiveIntegerField(default=20, help_text='Максимальное количество мест в читальном зале', verbose_name='вместимость')),
                ('has_computers', models.BooleanField(default=False, verbose_name='наличие компьютеров')),
                ('opening_time', models.TimeField(default='08:00', verbose_name='время открытия')),
                ('closing_time', models.TimeField(default='20:00', verbose_name='время закрытия')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_rooms', to='library_app.branch', verbose_name='филиал')),
            ],
            options={
                'verbose_name': 'читальный зал',
                'verbose_name_plural': 'читальные залы',
                'ordering': ['branch', 'name'],
                'unique_together': {('name', 'branch')},
            },
        ),
    ]
