CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "library_app_author" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "last_name" varchar(100) NOT NULL, "first_name" varchar(100) NOT NULL, "middle_name" varchar(100) NULL);
CREATE TABLE IF NOT EXISTS "library_app_book" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(300) NOT NULL, "publication_year" integer unsigned NULL CHECK ("publication_year" >= 0), "page_count" integer unsigned NOT NULL CHECK ("page_count" >= 0), "illustration_count" integer unsigned NOT NULL CHECK ("illustration_count" >= 0), "price" decimal NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "publisher_id" bigint NULL REFERENCES "library_app_publisher" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "library_app_book_authors" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "book_id" bigint NOT NULL REFERENCES "library_app_book" ("id") DEFERRABLE INITIALLY DEFERRED, "author_id" bigint NOT NULL REFERENCES "library_app_author" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "library_app_branch" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL UNIQUE, "address" text NULL, "created_at" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "library_app_faculty" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL UNIQUE, "description" text NULL, "created_at" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "library_app_publisher" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL UNIQUE, "address" text NULL);
CREATE TABLE IF NOT EXISTS "library_app_student" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "last_name" varchar(100) NOT NULL, "first_name" varchar(100) NOT NULL, "student_id" varchar(20) NOT NULL UNIQUE, "created_at" datetime NOT NULL, "faculty_id" bigint NOT NULL REFERENCES "library_app_faculty" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "library_app_loan" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "issue_date" datetime NOT NULL, "return_date" datetime NULL, "is_returned" bool NOT NULL, "book_id" bigint NOT NULL REFERENCES "library_app_book" ("id") DEFERRABLE INITIALLY DEFERRED, "branch_id" bigint NOT NULL REFERENCES "library_app_branch" ("id") DEFERRABLE INITIALLY DEFERRED, "created_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "student_id" bigint NOT NULL REFERENCES "library_app_student" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "library_app_bookinventory" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "total_copies" integer unsigned NOT NULL CHECK ("total_copies" >= 0), "available_copies" integer unsigned NOT NULL CHECK ("available_copies" >= 0), "last_updated" datetime NOT NULL, "book_id" bigint NOT NULL REFERENCES "library_app_book" ("id") DEFERRABLE INITIALLY DEFERRED, "branch_id" bigint NOT NULL REFERENCES "library_app_branch" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "library_app_bookfacultyusage" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "book_id" bigint NOT NULL REFERENCES "library_app_book" ("id") DEFERRABLE INITIALLY DEFERRED, "branch_id" bigint NOT NULL REFERENCES "library_app_branch" ("id") DEFERRABLE INITIALLY DEFERRED, "faculty_id" bigint NOT NULL REFERENCES "library_app_faculty" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "library_app_student_447a47_idx" ON "library_app_student" ("student_id");
CREATE INDEX "library_app_last_na_e17743_idx" ON "library_app_student" ("last_name", "first_name");
CREATE INDEX "library_app_issue_d_ab8064_idx" ON "library_app_loan" ("issue_date");
CREATE INDEX "library_app_is_retu_f295fe_idx" ON "library_app_loan" ("is_returned");
CREATE UNIQUE INDEX "library_app_bookinventory_book_id_branch_id_83e07e5f_uniq" ON "library_app_bookinventory" ("book_id", "branch_id");
CREATE UNIQUE INDEX "library_app_bookfacultyusage_book_id_branch_id_faculty_id_ee807929_uniq" ON "library_app_bookfacultyusage" ("book_id", "branch_id", "faculty_id");
CREATE INDEX "library_app_title_ec677d_idx" ON "library_app_book" ("title");
CREATE INDEX "library_app_publica_a46121_idx" ON "library_app_book" ("publication_year");
CREATE UNIQUE INDEX "library_app_author_last_name_first_name_middle_name_83e9f1b8_uniq" ON "library_app_author" ("last_name", "first_name", "middle_name");
CREATE UNIQUE INDEX "library_app_book_authors_book_id_author_id_207d38e6_uniq" ON "library_app_book_authors" ("book_id", "author_id");
CREATE INDEX "library_app_book_authors_book_id_882939bb" ON "library_app_book_authors" ("book_id");
CREATE INDEX "library_app_book_authors_author_id_b9065aec" ON "library_app_book_authors" ("author_id");
CREATE INDEX "library_app_student_faculty_id_c3f659cd" ON "library_app_student" ("faculty_id");
CREATE INDEX "library_app_loan_book_id_c1c7caae" ON "library_app_loan" ("book_id");
CREATE INDEX "library_app_loan_branch_id_e84bee9a" ON "library_app_loan" ("branch_id");
CREATE INDEX "library_app_loan_created_by_id_740bc4d8" ON "library_app_loan" ("created_by_id");
CREATE INDEX "library_app_loan_student_id_f91b666e" ON "library_app_loan" ("student_id");
CREATE INDEX "library_app_bookinventory_book_id_2fb41e12" ON "library_app_bookinventory" ("book_id");
CREATE INDEX "library_app_bookinventory_branch_id_6319b50f" ON "library_app_bookinventory" ("branch_id");
CREATE INDEX "library_app_bookfacultyusage_book_id_1ee85f8f" ON "library_app_bookfacultyusage" ("book_id");
CREATE INDEX "library_app_bookfacultyusage_branch_id_e34de4ab" ON "library_app_bookfacultyusage" ("branch_id");
CREATE INDEX "library_app_bookfacultyusage_faculty_id_687f66c5" ON "library_app_bookfacultyusage" ("faculty_id");
CREATE INDEX "library_app_book_publisher_id_140c2820" ON "library_app_book" ("publisher_id");
